### ISSUE TITLE
Marked by Windows Security

### ISSUE THREAD

**Issue by asshuka** [Vhou-Atroph/MHRise-Hunt-Chooser#2]
What title says.
![211003_23-13-57](https://user-images.githubusercontent.com/80346620/135762511-27ff9ba9-d71c-4de1-9c33-6985f6caac74.png)
I've looked this up a bit and I think an appeal can be submitted to Microsoft, but only the app's dev can submit it :0

**Comment by Vhou-Atroph** [comment]
Thanks for the information, I've submitted the file to Microsoft for scanning and will close this issue once Microsoft accepts the file.

**Comment by Vhou-Atroph** [comment]
After obtaining the latest malware definitions, the executable for version 2.2 will no longer be falsely identified as a virus by Windows Defender. Again, thank you for the report.
